### ISSUE TITLE
Decision over the CUAV flight controller

### ISSUE THREAD

**Issue by omuryildirim** [MichaelThamm/drone-project#1]
Hey Michael!

First of all great work! I'm glad that you decided to make everything public and document as much as possible. Recently, I started researching to create an autonomous drone system. Once I started I figured quickly that PX4 and Ardupilot is the way forward. 

As I researched I saw that CUAV, Cube and etc. are specialized on providing such flight controllers works with PX4 and Ardupilot. But then I read Ardupilot's docs about [common autopilot hardwares](https://ardupilot.org/copter/docs/common-autopilots.html). So I decided to buy a F405 stack and load Ardupilot firmware on it, e.g. [Mamba F405](https://ardupilot.org/copter/docs/common-mambaf405-mini.html#loading-firmware). I'm still deciding on my hardware so I didn't buy anything yet. I just wanted to ask if you tried to use Ardupilot with F7 flight controller before moving towards to CUAV nano FC? Also there is no information about the propellers you use, I assume they are 3 inch?

PS. My goal is to make a small and light UAV that will work indoor with >30 minutes flight time. So my target size is under 4 inch propellers and ideally 150mm frames with <300 grams weight. Thinking in that direction, CUAV kind of FCs are generally heavier than what I would like to have. Potentially I will not use Raspberry Pi onboard but will transfer the data from UAV to base computer.

PS.2. I saw your reddit post that's why I know you also considered to use F7 flight controller before using CUAV😅

**Comment by MichaelThamm** [comment]
Hello Ömür,

I did try to get this to work with the Speedybee F405 v3 stack and realized quite quickly that the autopilots were the way to go. The main reason being "The speedybee stack is designed for betaflight which is popular for FPV but has little/no autonomous support. Betaflight doesn't even have GPS position hold which should basically make it a non-starter. All the development effort in Betaflight goes for freestyle flying - so the speedybee stack will be good for a stunt drone."

If you plan to use this drone outdoors, I suggest you get yourself an autopilot (I chose CUAV mainly for cost). If you don't plan to use GPS for positioning (e.g. an indoor drone) then this will be a big headache for, see this: [EKF](https://discuss.ardupilot.org/t/arducopter-dronekit-arming-without-gps/113093/3) post. Overall Ardupilot is the way to go so whatever you choose, make sure to flash it with Ardupilot.

Important: make sure not to buy the Speedybee 50A BLS ESC, instead buy the Speedybee 50A BLHeli_S because it allows bi-directional communication. Otherwise you will lose money like I did :)

Lastly, I would check this out if you want to avoid using an Autopilot.  Rishabh Singh - [oak-on-drones](https://docs.luxonis.com/en/latest/pages/oak_on_drones/) [part-1](https://discuss.ardupilot.org/t/easy-way-to-integrate-ai-with-ardupilot-oak-d-part-1/79306) and [part-2](https://discuss.ardupilot.org/t/easy-way-to-integrate-ai-with-ardupilot-oak-d-part-2/79307).

Best of luck!

**Comment by omuryildirim** [comment]
Hey Michael!

Thanks a lot for the input and wishes! I will rethink the flight controller selection according to Ardupilot features again. I will update here if I will ever go the route of using F4 flight controllers with Ardupilot.

I checked ESCs after you mentioned the issue. I wonder if you mean to go for `BLHeli_32` instead of `BLHeli_S`. According to Speedybee specs `BLHeli_32 ` supports ESC telemetry but BLHeli_S doesn't. 

Although Ardupilot [Bi-directional DShot docs](https://ardupilot.org/copter/docs/common-esc-telemetry.html#bi-directional-dshot) mention;

>  Newer versions of BLHeli32 (32.7 and higher) and BLHeli_S (16.73 and higher) support returning motor RPM values over the DShot signal line.

But I think since there is no telemetry output pin for `BLHeli_S ` Speedybee ESC boards, they are not unusable to use with Ardupilot.

**Comment by omuryildirim** [comment]
Hey Michael!

Thanks a lot for the input and wishes! I will rethink the flight controller selection according to Ardupilot features again. I will update here if I will ever go the route of using F4 flight controllers with Ardupilot.

I checked ESCs after you mentioned the issue. I wonder if you mean to go for `BLHeli_32` instead of `BLHeli_S`. According to Speedybee specs `BLHeli_32 ` supports ESC telemetry but `BLHeli_S ` doesn't. 

Although Ardupilot [Bi-directional DShot docs](https://ardupilot.org/copter/docs/common-esc-telemetry.html#bi-directional-dshot) mention;

>  Newer versions of BLHeli32 (32.7 and higher) and BLHeli_S (16.73 and higher) support returning motor RPM values over the DShot signal line.

But I think since there is no telemetry output pin for `BLHeli_S ` Speedybee ESC boards, they are not usable with Ardupilot.

**Comment by MichaelThamm** [comment]
Yes, BL32 ESC is the way to go due to bi-directional DSHOT.

Cheers,

**Comment by MichaelThamm** [comment]
In hindsight BLH32 was not the way to go because they are discontinued. BLHeli_S with BlueJay flashed is best!
